/*
 * NetworkPrefsPanel2.java
 *
 * Created on September 23, 2010, 3:21 PM
 */

package multiplicity3.config.network;

import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

import multiplicity3.config.ConfigurationApplication;
import multiplicity3.config.network.xmpp.XMPPConfigPrefsItem;
import multiplicity3.config.network.xmpp.XMPPPrefsPanel;

/**
 *
 * @author  dcs0ah1
 */
public class NetworkPreferencesPanel extends javax.swing.JPanel {
	private static final long serialVersionUID = 7749882192186771339L;
	private NetworkConfigPrefsItem prefs;
    
    /** Creates new form NetworkPrefsPanel2 */
    public NetworkPreferencesPanel(NetworkConfigPrefsItem networkConfigPrefsItem) {
        this.prefs = networkConfigPrefsItem;
        initComponents();
        loadPrefs();
    }
    
    private void loadPrefs() {
        txtProxyHost.setText(prefs.getProxyHost());
        txtProxyPort.setText(""+prefs.getProxyPort());
        checkProxyEnabled.setSelected(prefs.getProxyEnabled());
        chkEnableNetworkSystem.setSelected(prefs.getNetworkSystemEnabled());
        comboNetworkSystem.setSelectedItem(prefs.getNetworkSystemClass());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProxyHost = new javax.swing.JTextField();
        txtProxyPort = new javax.swing.JTextField();
        checkProxyEnabled = new javax.swing.JCheckBox();
        comboNetworkSystem = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        chkEnableNetworkSystem = new javax.swing.JCheckBox();
        btnConfigure = new javax.swing.JButton();

        jLabel1.setText("HTTP Proxy Host:");

        jLabel2.setText("HTTP Proxy Port:");

        txtProxyHost.setText("jTextField1");
        txtProxyHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProxyHostKeyReleased(evt);
            }
        });

        txtProxyPort.setText("jTextField1");
        txtProxyPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProxyPortKeyReleased(evt);
            }
        });

        checkProxyEnabled.setText("Proxy Enabled");
        checkProxyEnabled.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        checkProxyEnabled.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkProxyEnabledItemStateChanged(evt);
            }
        });

        comboNetworkSystem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "multiplicity.network.xmpp.XMPPMultiplicityNetworkManager" }));
        comboNetworkSystem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboNetworkSystemItemStateChanged(evt);
            }
        });

        jLabel3.setText("Select a class that implements IMultiplicityNetworkManager:");

        chkEnableNetworkSystem.setText("Network system enabled:");
        chkEnableNetworkSystem.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        chkEnableNetworkSystem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkEnableNetworkSystemItemStateChanged(evt);
            }
        });

        btnConfigure.setText("Configure");
        btnConfigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProxyPort)
                            .addComponent(txtProxyHost, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(checkProxyEnabled))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(chkEnableNetworkSystem))
                            .addComponent(comboNetworkSystem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfigure)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProxyHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkProxyEnabled)
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboNetworkSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfigure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkEnableNetworkSystem)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void txtProxyHostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProxyHostKeyReleased
    prefs.setProxyHost(txtProxyHost.getText());
}//GEN-LAST:event_txtProxyHostKeyReleased

private void txtProxyPortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProxyPortKeyReleased
    int currentPort = prefs.getProxyPort();
    try {
        prefs.setProxyPort(Integer.parseInt(txtProxyPort.getText()));
    }catch(NumberFormatException ex) {
        JOptionPane.showMessageDialog(this,
            "Can't convert " + txtProxyPort.getText() + " to a number.",
            "Port should be an integer number.",
            JOptionPane.ERROR_MESSAGE);
        txtProxyPort.setText(""+currentPort);
    }
}//GEN-LAST:event_txtProxyPortKeyReleased

private void checkProxyEnabledItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkProxyEnabledItemStateChanged

    prefs.setProxyEnabled(checkProxyEnabled.isSelected());
}//GEN-LAST:event_checkProxyEnabledItemStateChanged

private void btnConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigureActionPerformed
switch(comboNetworkSystem.getSelectedIndex()){
    case 0: { break;}
    case 1: {
        XMPPPrefsPanel panel = new XMPPPrefsPanel(new XMPPConfigPrefsItem());
        JTabbedPane jtp = ConfigurationApplication.getTabbedPane();
        jtp.add("XMPP Prefs", panel);
        jtp.setSelectedComponent(panel);
        break;
    }
}
}//GEN-LAST:event_btnConfigureActionPerformed

private void chkEnableNetworkSystemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkEnableNetworkSystemItemStateChanged
    prefs.setNetworkSystemEnabled(chkEnableNetworkSystem.isSelected());
}//GEN-LAST:event_chkEnableNetworkSystemItemStateChanged

private void comboNetworkSystemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboNetworkSystemItemStateChanged
prefs.setNetworkSystemClass((String)comboNetworkSystem.getSelectedItem());
}//GEN-LAST:event_comboNetworkSystemItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfigure;
    private javax.swing.JCheckBox checkProxyEnabled;
    private javax.swing.JCheckBox chkEnableNetworkSystem;
    private javax.swing.JComboBox comboNetworkSystem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtProxyHost;
    private javax.swing.JTextField txtProxyPort;
    // End of variables declaration//GEN-END:variables

}
